name: Control Push
on: push
jobs:
  Job_qa:
    name: Job1 Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Step1 Checkout on master
        uses: actions/checkout@v3

      - name: Step2 Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Step2 Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Step4 Run tests
        run: |
          python -m pytest

      - name: Step5 Run flake8
        uses: py-actions/flake8@v2
